spring.application.name=inventario

spring.datasource.url=jdbc:h2:mem:inventariodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-plataform=org.hibernate.dialect.H2Dialect
Spring.h2.console.enable=true


spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.use-root-path=true
springdoc.api-docs.enable=true
